# Generated by Django 3.0.8 on 2021-07-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
