# Generated by Django 3.0.8 on 2021-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20210709_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
