# Generated by Django 3.0.8 on 2021-07-05 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('preferred_skills', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('additional_skills', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Undisclosed', 'Undisclosed')], max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('Junior Level', 'Junior Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Undisclosed', 'Undisclosed')], max_length=100, null=True)),
                ('qualifiction_type', models.CharField(blank=True, choices=[('Doctoral degree', 'Doctoral degree'), ('Masters Degree', 'Masters Degree'), ('Graduate Diploma', 'Graduate Diploma'), ('Bachelor Degree', 'Bachelor Degree'), ('Advanced Diploma / Associates Degree', 'Advanced Diploma / Associates degree'), ('Diploma', 'Diploma'), ('Professional Certificate', 'Professional Certificate'), ('Undisclosed', 'Undisclosed')], max_length=100, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('qualities', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.Category')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.Industry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.Location')),
            ],
        ),
    ]
