# Generated by Django 3.0.8 on 2021-07-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
